//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student_Fee
    {
        public int ID { get; set; }
        public int Fee_Type_Id { get; set; }
        public decimal Amount_Received { get; set; }
        public int Student_Id { get; set; }
        public Nullable<decimal> Amount_Pending { get; set; }
        public decimal Amount_Due { get; set; }
    }
}
