//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student
    {
        public int ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public int Class_Id { get; set; }
        public string Email { get; set; }
        public int Gender_Id { get; set; }
        public string Address { get; set; }
        public Nullable<int> Discount { get; set; }
        public string TutionFee { get; set; }
    }
}
